---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - import_tasks: tasks/token.yml

- hosts: prod
  connection: ssh
  gather_facts: true

  tasks:
    - import_tasks: tasks/hostid.yml
    - name: Get Roles from PCD
      uri:
        url: "{{ mgmt_url }}/resmgr/v1/hosts/{{ hostid }}/roles"
        method: GET
        headers:
          X-Auth-Token: "{{ hostvars['localhost']['keystone_token'] }}"
      with_inventory_hostnames: "{{ groups['pcd_prod'] }}"
