---
- name: Deploy OpenStack resources
  hosts: localhost
  gather_facts: false
  collections:
    - openstack.cloud

  tasks:
    - name: Upload image to glance
      openstack.cloud.image:
        cloud: sa-demo_admin
        name: cirros
        filename: /path/to/cirros.qcow2
        container_format: bare
        disk_format: qcow2
        state: present

    - name: Create network
      openstack.cloud.network:
        cloud: msa-demo_public
        state: present
        name: demo-net

    - name: Create subnet
      openstack.cloud.subnet:
        cloud: sa-demo_public
        network_name: demo-net
        cidr: 192.168.100.0/24
        ip_version: 4
        name: demo-subnet

    - name: Create volume
      openstack.cloud.volume:
        cloud: sa-demo_public
        display_name: demo-volume
        size: 3
        volume_type: lvm
        state: present

    - name: Create instance
      openstack.cloud.server:
        cloud: msa-demo_public
        state: present
        name: demo-vm
        image: cirros
        flavor: m1.small
        network: demo-net
        boot_from_volume: yes
        terminate_volume: true
        volumes:
          - demo-volume