---
- name: Set PCD Roles
  pf9.pcd.roles:
    state: "{{ storage | default('present') }}"
    mgmt_url: "{{ hostvars['localhost']['pcd_region_portal'] }}"
    token: "{{ keystone_token }}"
    roles: "persistent-storage"
    persistent_storage: "{{ persistent_storage }}"
    host_id: "{{ hostid }}"
    hostconfig: "{{ hostconfig }}"
