#cloud-config

write_files:
  - path: /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg
    permissions: "0644"
    content: |
      network: {config: disabled}

  - path: /etc/netplan/99-custom.yaml
    permissions: "0644"
    content: |
      network:
        version: 2
        renderer: networkd
        ethernets:
          enp94s0f0:
            dhcp4: false
          enp24s0f1:
            dhcp4: false
        bonds:
          bond0:
            interfaces:
              - enp24s0f1
              - enp94s0f0
            parameters:
              mode: active-backup
              primary: enp24s0f1
              mii-monitor-interval: 100
            dhcp4: false
            addresses:
              - $ip/24
            routes:
              - to: default
                via: 192.168.125.254
            nameservers:
              addresses:
                - 8.8.8.8

runcmd:
  - rm -f /etc/netplan/50-cloud-init.yaml
  - netplan apply

